#ifndef LIBCRSF_DEF_H
#define LIBCRSF_DEF_H

#include <sdkconfig.h>

#ifdef CONFIG_LIBCRSF_PARAM_MAX_COUNT 
#define CRSF_DEVICE_PARAM_MAX_COUNT CONFIG_LIBCRSF_PARAM_MAX_COUNT
#else
#define CRSF_DEVICE_PARAM_MAX_COUNT 10
#endif

#ifdef CONFIG_LIBCRSF_PARAM_SELECT_OPTION_MAX_COUNT 
#define CRSF_DEVICE_PARAM_SELECT_MAX_OPTION_COUNT CONFIG_LIBCRSF_PARAM_SELECT_OPTION_MAX_COUNT 
#else
#define CONFIG_LIBCRSF_PARAM_SELECT_OPTION_MAX_COUNT 10
#endif

#endif
