"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EstimateState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EstimateStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EstimateState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Unstable: _EstimateState.ValueType  # 0
    """the estimate is not (yet) stable and must not be used"""
    Stable: _EstimateState.ValueType  # 1
    """the estimate is stable and can be used"""

class EstimateState(_EstimateState, metaclass=_EstimateStateEnumTypeWrapper): ...

Unstable: EstimateState.ValueType  # 0
"""the estimate is not (yet) stable and must not be used"""
Stable: EstimateState.ValueType  # 1
"""the estimate is stable and can be used"""
global___EstimateState = EstimateState

class _ClientState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ClientStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ClientState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NotReady: _ClientState.ValueType  # 0
    """the client is not ready to engage"""
    Ready: _ClientState.ValueType  # 1
    """the client is ready to engage"""
    Engaging: _ClientState.ValueType  # 2
    """the client is currently engaging a target"""

class ClientState(_ClientState, metaclass=_ClientStateEnumTypeWrapper): ...

NotReady: ClientState.ValueType  # 0
"""the client is not ready to engage"""
Ready: ClientState.ValueType  # 1
"""the client is ready to engage"""
Engaging: ClientState.ValueType  # 2
"""the client is currently engaging a target"""
global___ClientState = ClientState

@typing.final
class Timestamp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    nanos: builtins.int
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nanos", b"nanos", "seconds", b"seconds"]) -> None: ...

global___Timestamp = Timestamp

@typing.final
class TargetEstimate(google.protobuf.message.Message):
    """Target state estimate"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    PRECISE_TIMESTAMP_FIELD_NUMBER: builtins.int
    TARGET_ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    VELOCITY_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    UNCERTAINTIES_FIELD_NUMBER: builtins.int
    precise_timestamp: builtins.bool
    """true if timestamp comes from high-precision source (such as GPS"""
    target_id: builtins.str
    """synchronized time), false otherwise
    unique identifier for the object as reported by the radar
    """
    state: global___EstimateState.ValueType
    """state of the estimate"""
    @property
    def timestamp(self) -> global___Timestamp:
        """timestamp of the radar point, in UTC, up to nanosecond precision"""

    @property
    def position(self) -> global___WGS84:
        """position of the object in WGS84 coordinates"""

    @property
    def velocity(self) -> global___EnuVelocity:
        """velocity of the object, in ENU coordinates, m/s"""

    @property
    def uncertainties(self) -> global___EstimateUncertainties:
        """[optional] uncertainties of the estimate"""

    def __init__(
        self,
        *,
        timestamp: global___Timestamp | None = ...,
        precise_timestamp: builtins.bool = ...,
        target_id: builtins.str = ...,
        position: global___WGS84 | None = ...,
        velocity: global___EnuVelocity | None = ...,
        state: global___EstimateState.ValueType = ...,
        uncertainties: global___EstimateUncertainties | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["position", b"position", "timestamp", b"timestamp", "uncertainties", b"uncertainties", "velocity", b"velocity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["position", b"position", "precise_timestamp", b"precise_timestamp", "state", b"state", "target_id", b"target_id", "timestamp", b"timestamp", "uncertainties", b"uncertainties", "velocity", b"velocity"]) -> None: ...

global___TargetEstimate = TargetEstimate

@typing.final
class RawData(google.protobuf.message.Message):
    """Raw data from the radar"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_UTC_FIELD_NUMBER: builtins.int
    TRACK_ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    POSITION_UNCERTAINTY_FIELD_NUMBER: builtins.int
    track_id: builtins.int
    """unique identifier for the object track as reported by the radar"""
    @property
    def timestamp_utc(self) -> global___Timestamp:
        """timestamp of the radar point, in UTC, up to nanosecond precision"""

    @property
    def position(self) -> global___WGS84:
        """position of the object in WGS84 coordinates"""

    @property
    def position_uncertainty(self) -> global___EnuUncertainty:
        """uncertainties of the position estimate"""

    def __init__(
        self,
        *,
        timestamp_utc: global___Timestamp | None = ...,
        track_id: builtins.int = ...,
        position: global___WGS84 | None = ...,
        position_uncertainty: global___EnuUncertainty | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["position", b"position", "position_uncertainty", b"position_uncertainty", "timestamp_utc", b"timestamp_utc"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["position", b"position", "position_uncertainty", b"position_uncertainty", "timestamp_utc", b"timestamp_utc", "track_id", b"track_id"]) -> None: ...

global___RawData = RawData

@typing.final
class EstimateUncertainties(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    VELOCITY_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> global___EnuUncertainty:
        """uncertainties of the position estimate"""

    @property
    def velocity(self) -> global___EnuUncertainty:
        """uncertainties of the velocity estimate"""

    def __init__(
        self,
        *,
        position: global___EnuUncertainty | None = ...,
        velocity: global___EnuUncertainty | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["position", b"position", "velocity", b"velocity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["position", b"position", "velocity", b"velocity"]) -> None: ...

global___EstimateUncertainties = EstimateUncertainties

@typing.final
class WGS84(google.protobuf.message.Message):
    """Geodesic position in WGS84 coordinates"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATITUDE_DEG_FIELD_NUMBER: builtins.int
    LONGITUDE_DEG_FIELD_NUMBER: builtins.int
    ALTITUDE_MSL_M_FIELD_NUMBER: builtins.int
    latitude_deg: builtins.float
    longitude_deg: builtins.float
    altitude_msl_m: builtins.float
    def __init__(
        self,
        *,
        latitude_deg: builtins.float = ...,
        longitude_deg: builtins.float = ...,
        altitude_msl_m: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["altitude_msl_m", b"altitude_msl_m", "latitude_deg", b"latitude_deg", "longitude_deg", b"longitude_deg"]) -> None: ...

global___WGS84 = WGS84

@typing.final
class EnuVelocity(google.protobuf.message.Message):
    """Velocity in local ENU coordinates"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EAST_MS_FIELD_NUMBER: builtins.int
    NORTH_MS_FIELD_NUMBER: builtins.int
    UP_MS_FIELD_NUMBER: builtins.int
    east_ms: builtins.float
    north_ms: builtins.float
    up_ms: builtins.float
    def __init__(
        self,
        *,
        east_ms: builtins.float = ...,
        north_ms: builtins.float = ...,
        up_ms: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["east_ms", b"east_ms", "north_ms", b"north_ms", "up_ms", b"up_ms"]) -> None: ...

global___EnuVelocity = EnuVelocity

@typing.final
class EnuUncertainty(google.protobuf.message.Message):
    """Uncertainty in local ENU coordinates"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EAST_FIELD_NUMBER: builtins.int
    NORTH_FIELD_NUMBER: builtins.int
    UP_FIELD_NUMBER: builtins.int
    east: builtins.float
    north: builtins.float
    up: builtins.float
    def __init__(
        self,
        *,
        east: builtins.float = ...,
        north: builtins.float = ...,
        up: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["east", b"east", "north", b"north", "up", b"up"]) -> None: ...

global___EnuUncertainty = EnuUncertainty

@typing.final
class Ping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Ping = Ping

@typing.final
class ServerMessage(google.protobuf.message.Message):
    """Messages sent from the server to the end-user"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PING_FIELD_NUMBER: builtins.int
    TARGET_ESTIMATE_FIELD_NUMBER: builtins.int
    INTERCEPTOR_ESTIMATE_FIELD_NUMBER: builtins.int
    TARGET_RAW_FIELD_NUMBER: builtins.int
    INTERCEPTOR_RAW_FIELD_NUMBER: builtins.int
    @property
    def ping(self) -> global___Ping: ...
    @property
    def target_estimate(self) -> global___TargetEstimate: ...
    @property
    def interceptor_estimate(self) -> global___TargetEstimate: ...
    @property
    def target_raw(self) -> global___RawData: ...
    @property
    def interceptor_raw(self) -> global___RawData: ...
    def __init__(
        self,
        *,
        ping: global___Ping | None = ...,
        target_estimate: global___TargetEstimate | None = ...,
        interceptor_estimate: global___TargetEstimate | None = ...,
        target_raw: global___RawData | None = ...,
        interceptor_raw: global___RawData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["interceptor_estimate", b"interceptor_estimate", "interceptor_raw", b"interceptor_raw", "message", b"message", "ping", b"ping", "target_estimate", b"target_estimate", "target_raw", b"target_raw"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["interceptor_estimate", b"interceptor_estimate", "interceptor_raw", b"interceptor_raw", "message", b"message", "ping", b"ping", "target_estimate", b"target_estimate", "target_raw", b"target_raw"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["message", b"message"]) -> typing.Literal["ping", "target_estimate", "interceptor_estimate", "target_raw", "interceptor_raw"] | None: ...

global___ServerMessage = ServerMessage

@typing.final
class ClientStatus(google.protobuf.message.Message):
    """Current status of the client"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    state: global___ClientState.ValueType
    @property
    def position(self) -> global___WGS84:
        """[optional]"""

    def __init__(
        self,
        *,
        state: global___ClientState.ValueType = ...,
        position: global___WGS84 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["position", b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["position", b"position", "state", b"state"]) -> None: ...

global___ClientStatus = ClientStatus

@typing.final
class Channels(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CH1_FIELD_NUMBER: builtins.int
    CH2_FIELD_NUMBER: builtins.int
    CH3_FIELD_NUMBER: builtins.int
    CH4_FIELD_NUMBER: builtins.int
    ch1: builtins.int
    ch2: builtins.int
    ch3: builtins.int
    ch4: builtins.int
    def __init__(
        self,
        *,
        ch1: builtins.int = ...,
        ch2: builtins.int = ...,
        ch3: builtins.int = ...,
        ch4: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ch1", b"ch1", "ch2", b"ch2", "ch3", b"ch3", "ch4", b"ch4"]) -> None: ...

global___Channels = Channels

@typing.final
class ClientMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    @property
    def status(self) -> global___ClientStatus: ...
    @property
    def channels(self) -> global___Channels: ...
    def __init__(
        self,
        *,
        status: global___ClientStatus | None = ...,
        channels: global___Channels | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["channels", b"channels", "message", b"message", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["channels", b"channels", "message", b"message", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["message", b"message"]) -> typing.Literal["status", "channels"] | None: ...

global___ClientMessage = ClientMessage
