/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "skymap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ai_skyfortress_guidance_Timestamp, ai_skyfortress_guidance_Timestamp, AUTO)


PB_BIND(ai_skyfortress_guidance_TargetEstimate, ai_skyfortress_guidance_TargetEstimate, AUTO)


PB_BIND(ai_skyfortress_guidance_RawData, ai_skyfortress_guidance_RawData, AUTO)


PB_BIND(ai_skyfortress_guidance_EstimateUncertainties, ai_skyfortress_guidance_EstimateUncertainties, AUTO)


PB_BIND(ai_skyfortress_guidance_WGS84, ai_skyfortress_guidance_WGS84, AUTO)


PB_BIND(ai_skyfortress_guidance_EnuVelocity, ai_skyfortress_guidance_EnuVelocity, AUTO)


PB_BIND(ai_skyfortress_guidance_EnuUncertainty, ai_skyfortress_guidance_EnuUncertainty, AUTO)


PB_BIND(ai_skyfortress_guidance_Ping, ai_skyfortress_guidance_Ping, AUTO)


PB_BIND(ai_skyfortress_guidance_ServerMessage, ai_skyfortress_guidance_ServerMessage, AUTO)


PB_BIND(ai_skyfortress_guidance_ClientStatus, ai_skyfortress_guidance_ClientStatus, AUTO)


PB_BIND(ai_skyfortress_guidance_ClientMessage, ai_skyfortress_guidance_ClientMessage, AUTO)







