/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AI_SKYFORTRESS_GUIDANCE_SKYMAP_PB_H_INCLUDED
#define PB_AI_SKYFORTRESS_GUIDANCE_SKYMAP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ai_skyfortress_guidance_EstimateState {
    ai_skyfortress_guidance_EstimateState_Unstable = 0, /* the estimate is not (yet) stable and must not be used */
    ai_skyfortress_guidance_EstimateState_Stable = 1 /* the estimate is stable and can be used */
} ai_skyfortress_guidance_EstimateState;

typedef enum _ai_skyfortress_guidance_ClientState {
    ai_skyfortress_guidance_ClientState_NotReady = 0, /* the client is not ready to engage */
    ai_skyfortress_guidance_ClientState_Ready = 1, /* the client is ready to engage */
    ai_skyfortress_guidance_ClientState_Engaging = 2 /* the client is currently engaging a target */
} ai_skyfortress_guidance_ClientState;

/* Struct definitions */
typedef struct _ai_skyfortress_guidance_Timestamp {
    int64_t seconds;
    int32_t nanos;
} ai_skyfortress_guidance_Timestamp;

/* Geodesic position in WGS84 coordinates */
typedef struct _ai_skyfortress_guidance_WGS84 {
    float latitude_deg;
    float longitude_deg;
    float altitude_msl_m;
} ai_skyfortress_guidance_WGS84;

/* Velocity in local ENU coordinates */
typedef struct _ai_skyfortress_guidance_EnuVelocity {
    float east_ms;
    float north_ms;
    float up_ms;
} ai_skyfortress_guidance_EnuVelocity;

/* Uncertainty in local ENU coordinates */
typedef struct _ai_skyfortress_guidance_EnuUncertainty {
    float east;
    float north;
    float up;
} ai_skyfortress_guidance_EnuUncertainty;

/* Raw data from the radar */
typedef struct _ai_skyfortress_guidance_RawData {
    bool has_timestamp_utc;
    ai_skyfortress_guidance_Timestamp timestamp_utc; /* timestamp of the radar point, in UTC, up to nanosecond precision */
    uint32_t track_id; /* unique identifier for the object track as reported by the radar */
    bool has_position;
    ai_skyfortress_guidance_WGS84 position; /* position of the object in WGS84 coordinates */
    bool has_position_uncertainty;
    ai_skyfortress_guidance_EnuUncertainty position_uncertainty; /* uncertainties of the position estimate */
} ai_skyfortress_guidance_RawData;

typedef struct _ai_skyfortress_guidance_EstimateUncertainties {
    bool has_position;
    ai_skyfortress_guidance_EnuUncertainty position; /* uncertainties of the position estimate */
    bool has_velocity;
    ai_skyfortress_guidance_EnuUncertainty velocity; /* uncertainties of the velocity estimate */
} ai_skyfortress_guidance_EstimateUncertainties;

/* Target state estimate */
typedef struct _ai_skyfortress_guidance_TargetEstimate {
    bool has_timestamp;
    ai_skyfortress_guidance_Timestamp timestamp; /* timestamp of the radar point, in UTC, up to nanosecond precision */
    bool precise_timestamp; /* true if timestamp comes from high-precision source (such as GPS */
    /* synchronized time), false otherwise */
    pb_callback_t target_id; /* unique identifier for the object as reported by the radar */
    bool has_position;
    ai_skyfortress_guidance_WGS84 position; /* position of the object in WGS84 coordinates */
    bool has_velocity;
    ai_skyfortress_guidance_EnuVelocity velocity; /* velocity of the object, in ENU coordinates, m/s */
    ai_skyfortress_guidance_EstimateState state; /* state of the estimate */
    bool has_uncertainties;
    ai_skyfortress_guidance_EstimateUncertainties uncertainties; /* [optional] uncertainties of the estimate */
} ai_skyfortress_guidance_TargetEstimate;

typedef struct _ai_skyfortress_guidance_Ping {
    char dummy_field;
} ai_skyfortress_guidance_Ping;

/* Messages sent from the server to the end-user */
typedef struct _ai_skyfortress_guidance_ServerMessage {
    pb_size_t which_message;
    union {
        ai_skyfortress_guidance_Ping ping;
        ai_skyfortress_guidance_TargetEstimate target_estimate;
        ai_skyfortress_guidance_TargetEstimate interceptor_estimate;
        ai_skyfortress_guidance_RawData target_raw;
        ai_skyfortress_guidance_RawData target_interceptor;
    } message;
} ai_skyfortress_guidance_ServerMessage;

/* Current status of the client */
typedef struct _ai_skyfortress_guidance_ClientStatus {
    ai_skyfortress_guidance_ClientState state;
    bool has_position;
    ai_skyfortress_guidance_WGS84 position; /* [optional] */
} ai_skyfortress_guidance_ClientStatus;

typedef struct _ai_skyfortress_guidance_ClientMessage {
    pb_size_t which_message;
    union {
        ai_skyfortress_guidance_ClientStatus status;
    } message;
} ai_skyfortress_guidance_ClientMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ai_skyfortress_guidance_EstimateState_MIN ai_skyfortress_guidance_EstimateState_Unstable
#define _ai_skyfortress_guidance_EstimateState_MAX ai_skyfortress_guidance_EstimateState_Stable
#define _ai_skyfortress_guidance_EstimateState_ARRAYSIZE ((ai_skyfortress_guidance_EstimateState)(ai_skyfortress_guidance_EstimateState_Stable+1))

#define _ai_skyfortress_guidance_ClientState_MIN ai_skyfortress_guidance_ClientState_NotReady
#define _ai_skyfortress_guidance_ClientState_MAX ai_skyfortress_guidance_ClientState_Engaging
#define _ai_skyfortress_guidance_ClientState_ARRAYSIZE ((ai_skyfortress_guidance_ClientState)(ai_skyfortress_guidance_ClientState_Engaging+1))


#define ai_skyfortress_guidance_TargetEstimate_state_ENUMTYPE ai_skyfortress_guidance_EstimateState








#define ai_skyfortress_guidance_ClientStatus_state_ENUMTYPE ai_skyfortress_guidance_ClientState



/* Initializer values for message structs */
#define ai_skyfortress_guidance_Timestamp_init_default {0, 0}
#define ai_skyfortress_guidance_TargetEstimate_init_default {false, ai_skyfortress_guidance_Timestamp_init_default, 0, {{NULL}, NULL}, false, ai_skyfortress_guidance_WGS84_init_default, false, ai_skyfortress_guidance_EnuVelocity_init_default, _ai_skyfortress_guidance_EstimateState_MIN, false, ai_skyfortress_guidance_EstimateUncertainties_init_default}
#define ai_skyfortress_guidance_RawData_init_default {false, ai_skyfortress_guidance_Timestamp_init_default, 0, false, ai_skyfortress_guidance_WGS84_init_default, false, ai_skyfortress_guidance_EnuUncertainty_init_default}
#define ai_skyfortress_guidance_EstimateUncertainties_init_default {false, ai_skyfortress_guidance_EnuUncertainty_init_default, false, ai_skyfortress_guidance_EnuUncertainty_init_default}
#define ai_skyfortress_guidance_WGS84_init_default {0, 0, 0}
#define ai_skyfortress_guidance_EnuVelocity_init_default {0, 0, 0}
#define ai_skyfortress_guidance_EnuUncertainty_init_default {0, 0, 0}
#define ai_skyfortress_guidance_Ping_init_default {0}
#define ai_skyfortress_guidance_ServerMessage_init_default {0, {ai_skyfortress_guidance_Ping_init_default}}
#define ai_skyfortress_guidance_ClientStatus_init_default {_ai_skyfortress_guidance_ClientState_MIN, false, ai_skyfortress_guidance_WGS84_init_default}
#define ai_skyfortress_guidance_ClientMessage_init_default {0, {ai_skyfortress_guidance_ClientStatus_init_default}}
#define ai_skyfortress_guidance_Timestamp_init_zero {0, 0}
#define ai_skyfortress_guidance_TargetEstimate_init_zero {false, ai_skyfortress_guidance_Timestamp_init_zero, 0, {{NULL}, NULL}, false, ai_skyfortress_guidance_WGS84_init_zero, false, ai_skyfortress_guidance_EnuVelocity_init_zero, _ai_skyfortress_guidance_EstimateState_MIN, false, ai_skyfortress_guidance_EstimateUncertainties_init_zero}
#define ai_skyfortress_guidance_RawData_init_zero {false, ai_skyfortress_guidance_Timestamp_init_zero, 0, false, ai_skyfortress_guidance_WGS84_init_zero, false, ai_skyfortress_guidance_EnuUncertainty_init_zero}
#define ai_skyfortress_guidance_EstimateUncertainties_init_zero {false, ai_skyfortress_guidance_EnuUncertainty_init_zero, false, ai_skyfortress_guidance_EnuUncertainty_init_zero}
#define ai_skyfortress_guidance_WGS84_init_zero  {0, 0, 0}
#define ai_skyfortress_guidance_EnuVelocity_init_zero {0, 0, 0}
#define ai_skyfortress_guidance_EnuUncertainty_init_zero {0, 0, 0}
#define ai_skyfortress_guidance_Ping_init_zero   {0}
#define ai_skyfortress_guidance_ServerMessage_init_zero {0, {ai_skyfortress_guidance_Ping_init_zero}}
#define ai_skyfortress_guidance_ClientStatus_init_zero {_ai_skyfortress_guidance_ClientState_MIN, false, ai_skyfortress_guidance_WGS84_init_zero}
#define ai_skyfortress_guidance_ClientMessage_init_zero {0, {ai_skyfortress_guidance_ClientStatus_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ai_skyfortress_guidance_Timestamp_seconds_tag 1
#define ai_skyfortress_guidance_Timestamp_nanos_tag 2
#define ai_skyfortress_guidance_WGS84_latitude_deg_tag 1
#define ai_skyfortress_guidance_WGS84_longitude_deg_tag 2
#define ai_skyfortress_guidance_WGS84_altitude_msl_m_tag 3
#define ai_skyfortress_guidance_EnuVelocity_east_ms_tag 1
#define ai_skyfortress_guidance_EnuVelocity_north_ms_tag 2
#define ai_skyfortress_guidance_EnuVelocity_up_ms_tag 3
#define ai_skyfortress_guidance_EnuUncertainty_east_tag 1
#define ai_skyfortress_guidance_EnuUncertainty_north_tag 2
#define ai_skyfortress_guidance_EnuUncertainty_up_tag 3
#define ai_skyfortress_guidance_RawData_timestamp_utc_tag 1
#define ai_skyfortress_guidance_RawData_track_id_tag 3
#define ai_skyfortress_guidance_RawData_position_tag 4
#define ai_skyfortress_guidance_RawData_position_uncertainty_tag 5
#define ai_skyfortress_guidance_EstimateUncertainties_position_tag 1
#define ai_skyfortress_guidance_EstimateUncertainties_velocity_tag 2
#define ai_skyfortress_guidance_TargetEstimate_timestamp_tag 1
#define ai_skyfortress_guidance_TargetEstimate_precise_timestamp_tag 2
#define ai_skyfortress_guidance_TargetEstimate_target_id_tag 3
#define ai_skyfortress_guidance_TargetEstimate_position_tag 4
#define ai_skyfortress_guidance_TargetEstimate_velocity_tag 5
#define ai_skyfortress_guidance_TargetEstimate_state_tag 6
#define ai_skyfortress_guidance_TargetEstimate_uncertainties_tag 7
#define ai_skyfortress_guidance_ServerMessage_ping_tag 1
#define ai_skyfortress_guidance_ServerMessage_target_estimate_tag 2
#define ai_skyfortress_guidance_ServerMessage_interceptor_estimate_tag 3
#define ai_skyfortress_guidance_ServerMessage_target_raw_tag 4
#define ai_skyfortress_guidance_ServerMessage_target_interceptor_tag 5
#define ai_skyfortress_guidance_ClientStatus_state_tag 1
#define ai_skyfortress_guidance_ClientStatus_position_tag 2
#define ai_skyfortress_guidance_ClientMessage_status_tag 1

/* Struct field encoding specification for nanopb */
#define ai_skyfortress_guidance_Timestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1) \
X(a, STATIC,   SINGULAR, INT32,    nanos,             2)
#define ai_skyfortress_guidance_Timestamp_CALLBACK NULL
#define ai_skyfortress_guidance_Timestamp_DEFAULT NULL

#define ai_skyfortress_guidance_TargetEstimate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         1) \
X(a, STATIC,   SINGULAR, BOOL,     precise_timestamp,   2) \
X(a, CALLBACK, SINGULAR, STRING,   target_id,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velocity,          5) \
X(a, STATIC,   SINGULAR, UENUM,    state,             6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uncertainties,     7)
#define ai_skyfortress_guidance_TargetEstimate_CALLBACK pb_default_field_callback
#define ai_skyfortress_guidance_TargetEstimate_DEFAULT NULL
#define ai_skyfortress_guidance_TargetEstimate_timestamp_MSGTYPE ai_skyfortress_guidance_Timestamp
#define ai_skyfortress_guidance_TargetEstimate_position_MSGTYPE ai_skyfortress_guidance_WGS84
#define ai_skyfortress_guidance_TargetEstimate_velocity_MSGTYPE ai_skyfortress_guidance_EnuVelocity
#define ai_skyfortress_guidance_TargetEstimate_uncertainties_MSGTYPE ai_skyfortress_guidance_EstimateUncertainties

#define ai_skyfortress_guidance_RawData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp_utc,     1) \
X(a, STATIC,   SINGULAR, UINT32,   track_id,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position_uncertainty,   5)
#define ai_skyfortress_guidance_RawData_CALLBACK NULL
#define ai_skyfortress_guidance_RawData_DEFAULT NULL
#define ai_skyfortress_guidance_RawData_timestamp_utc_MSGTYPE ai_skyfortress_guidance_Timestamp
#define ai_skyfortress_guidance_RawData_position_MSGTYPE ai_skyfortress_guidance_WGS84
#define ai_skyfortress_guidance_RawData_position_uncertainty_MSGTYPE ai_skyfortress_guidance_EnuUncertainty

#define ai_skyfortress_guidance_EstimateUncertainties_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velocity,          2)
#define ai_skyfortress_guidance_EstimateUncertainties_CALLBACK NULL
#define ai_skyfortress_guidance_EstimateUncertainties_DEFAULT NULL
#define ai_skyfortress_guidance_EstimateUncertainties_position_MSGTYPE ai_skyfortress_guidance_EnuUncertainty
#define ai_skyfortress_guidance_EstimateUncertainties_velocity_MSGTYPE ai_skyfortress_guidance_EnuUncertainty

#define ai_skyfortress_guidance_WGS84_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude_deg,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude_deg,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude_msl_m,    3)
#define ai_skyfortress_guidance_WGS84_CALLBACK NULL
#define ai_skyfortress_guidance_WGS84_DEFAULT NULL

#define ai_skyfortress_guidance_EnuVelocity_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    east_ms,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    north_ms,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    up_ms,             3)
#define ai_skyfortress_guidance_EnuVelocity_CALLBACK NULL
#define ai_skyfortress_guidance_EnuVelocity_DEFAULT NULL

#define ai_skyfortress_guidance_EnuUncertainty_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    east,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    north,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    up,                3)
#define ai_skyfortress_guidance_EnuUncertainty_CALLBACK NULL
#define ai_skyfortress_guidance_EnuUncertainty_DEFAULT NULL

#define ai_skyfortress_guidance_Ping_FIELDLIST(X, a) \

#define ai_skyfortress_guidance_Ping_CALLBACK NULL
#define ai_skyfortress_guidance_Ping_DEFAULT NULL

#define ai_skyfortress_guidance_ServerMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ping,message.ping),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,target_estimate,message.target_estimate),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,interceptor_estimate,message.interceptor_estimate),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,target_raw,message.target_raw),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,target_interceptor,message.target_interceptor),   5)
#define ai_skyfortress_guidance_ServerMessage_CALLBACK NULL
#define ai_skyfortress_guidance_ServerMessage_DEFAULT NULL
#define ai_skyfortress_guidance_ServerMessage_message_ping_MSGTYPE ai_skyfortress_guidance_Ping
#define ai_skyfortress_guidance_ServerMessage_message_target_estimate_MSGTYPE ai_skyfortress_guidance_TargetEstimate
#define ai_skyfortress_guidance_ServerMessage_message_interceptor_estimate_MSGTYPE ai_skyfortress_guidance_TargetEstimate
#define ai_skyfortress_guidance_ServerMessage_message_target_raw_MSGTYPE ai_skyfortress_guidance_RawData
#define ai_skyfortress_guidance_ServerMessage_message_target_interceptor_MSGTYPE ai_skyfortress_guidance_RawData

#define ai_skyfortress_guidance_ClientStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2)
#define ai_skyfortress_guidance_ClientStatus_CALLBACK NULL
#define ai_skyfortress_guidance_ClientStatus_DEFAULT NULL
#define ai_skyfortress_guidance_ClientStatus_position_MSGTYPE ai_skyfortress_guidance_WGS84

#define ai_skyfortress_guidance_ClientMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,status,message.status),   1)
#define ai_skyfortress_guidance_ClientMessage_CALLBACK NULL
#define ai_skyfortress_guidance_ClientMessage_DEFAULT NULL
#define ai_skyfortress_guidance_ClientMessage_message_status_MSGTYPE ai_skyfortress_guidance_ClientStatus

extern const pb_msgdesc_t ai_skyfortress_guidance_Timestamp_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_TargetEstimate_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_RawData_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_EstimateUncertainties_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_WGS84_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_EnuVelocity_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_EnuUncertainty_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_Ping_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_ServerMessage_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_ClientStatus_msg;
extern const pb_msgdesc_t ai_skyfortress_guidance_ClientMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ai_skyfortress_guidance_Timestamp_fields &ai_skyfortress_guidance_Timestamp_msg
#define ai_skyfortress_guidance_TargetEstimate_fields &ai_skyfortress_guidance_TargetEstimate_msg
#define ai_skyfortress_guidance_RawData_fields &ai_skyfortress_guidance_RawData_msg
#define ai_skyfortress_guidance_EstimateUncertainties_fields &ai_skyfortress_guidance_EstimateUncertainties_msg
#define ai_skyfortress_guidance_WGS84_fields &ai_skyfortress_guidance_WGS84_msg
#define ai_skyfortress_guidance_EnuVelocity_fields &ai_skyfortress_guidance_EnuVelocity_msg
#define ai_skyfortress_guidance_EnuUncertainty_fields &ai_skyfortress_guidance_EnuUncertainty_msg
#define ai_skyfortress_guidance_Ping_fields &ai_skyfortress_guidance_Ping_msg
#define ai_skyfortress_guidance_ServerMessage_fields &ai_skyfortress_guidance_ServerMessage_msg
#define ai_skyfortress_guidance_ClientStatus_fields &ai_skyfortress_guidance_ClientStatus_msg
#define ai_skyfortress_guidance_ClientMessage_fields &ai_skyfortress_guidance_ClientMessage_msg

/* Maximum encoded size of messages (where known) */
/* ai_skyfortress_guidance_TargetEstimate_size depends on runtime parameters */
/* ai_skyfortress_guidance_ServerMessage_size depends on runtime parameters */
#define AI_SKYFORTRESS_GUIDANCE_SKYMAP_PB_H_MAX_SIZE ai_skyfortress_guidance_RawData_size
#define ai_skyfortress_guidance_ClientMessage_size 21
#define ai_skyfortress_guidance_ClientStatus_size 19
#define ai_skyfortress_guidance_EnuUncertainty_size 15
#define ai_skyfortress_guidance_EnuVelocity_size 15
#define ai_skyfortress_guidance_EstimateUncertainties_size 34
#define ai_skyfortress_guidance_Ping_size        0
#define ai_skyfortress_guidance_RawData_size     64
#define ai_skyfortress_guidance_Timestamp_size   22
#define ai_skyfortress_guidance_WGS84_size       15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
